---
apiVersion: v1
kind: Namespace
metadata:
  name: pgwatch2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgwatch2
  name: pgwatch2
  namespace: pgwatch2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgwatch2
  strategy: {}
  template:
    metadata:
      labels:
        app: pgwatch2
    spec:
      containers:
      - image: postgresai/pgwatch2:1.12.0-3
        name: pgwatch2
        resources: {}
        # FIXME: PORts
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgwatch2
  name: pgwatch2
  namespace: pgwatch2
spec:
  ports:
  - port: 123 # FIXME: here
    protocol: TCP
    targetPort: 123
  selector:
    app: pgwatch2
---
#https://github.com/killercoda/scenario-examples/blob/main/kubernetes-dashboard/step1.md